FROM python:3.12.7-slim

WORKDIR /app

COPY requirements.txt .
COPY .env .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000


CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]
